### ISSUE TITLE
Cannot start middleware on Ubuntu using Swissbit USB TSE

### ISSUE THREAD

**Issue by JonaLoeffler** [fiskaltrust/interface-doc#191] opened 2021-05-10 08:57 UTC
When executing the `test.sh` script, the middleware fails with the following output: 

`2021-05-10 10:48:05 [ERR] Failed to setup SecureSignaturCreationDevice Id 11251f3a-2e23-4924-9fe7-36ec10663049 from Package fiskaltrust.Middleware.SCU.DE.Swissbit, Version 1.3.19
System.Runtime.Serialization.SerializationException: Unable to find assembly 'fiskaltrust.Middleware.SCU.DE.Swissbit.Interop, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'.`

A full log is appended. Any help is appreciated.

Ubuntu: `20.04 LTS`
Mono: `Mono JIT compiler version 6.12.0.122 (tarball Mon Feb 22 17:50:20 UTC 2021)`
Nuget: `NuGet Version: 5.9.1.11`

[fiskaltrust.log](https://github.com/fiskaltrust/interface-doc/files/6450831/fiskaltrust.log)

**Comment by TSchmiedlechner** [comment] 2021-05-10 15:14
Hello @JonaLoeffler,
this might be related to a missing dependency, either `libc` or `glibc`. We've also documented this [here](https://docs.fiskaltrust.cloud/docs/product-description/germany/products-and-services/caas/features/basics/tse/swissbit#troubleshooting). 

Does installing these packages resolves the issue for you?

**Comment by JonaLoeffler** [comment] 2021-05-10 16:01
If my understanding is correct, `glibc` is already installed via the `libc6` apt package. `ldd --version` reports that I am using version 2.31.
Any further ideas?

**Comment by JonaLoeffler** [comment] 2021-05-12 12:37
I guess I should have mentioned we are planning to run our system on a Raspberry PI 4, which has an ARM processor. 

The Swissbit SDK as well as your zip file don't seem to include a binary for ARM?

In the Swissbit SDK, however, there is a directory `arm` containing a single file `libWormAPI.so` although I am not sure what to do with that.

**Comment by TSchmiedlechner** [comment] 2021-06-15 07:07
Ah, thanks for clarifying. We currently don't have a Raspberry available to reproduce this issue, unfortunately, but it indeed might be related to non-loaded native libs on ARM64. 

If the issue is still relevant to you, could you please update the Swissbit SCU to 1.3.20 (in which we improved the error logging), and send us a full log file? Thanks alot, we'll also try to get our hands on a Raspberry Pi to reproduce and hopefully resolve this issue.

**Comment by JonaLoeffler** [comment] 2021-06-15 08:36
This is not actually relevant for us anymore, as we've decided to implement the Fiskaly solution directly. We do lose offline capabiities, but so far the implementation process seems much more straightforward.

Anyways, thanks for your support.

**Comment by TSchmiedlechner** [comment] 2021-06-15 11:59
Okay, I'm sorry to hear that, but of course understand your decision. We'll move tracking ARM64 support to our internal workitem tracking in that case and close this issue.

**Closed by TSchmiedlechner** 2021-06-15 11:59 UTC
Labels: enhancement, future-version, scu
